accounts/urls.py
from rest_framework_jwt.views import obtain_jwt_token
from rest_framework_jwt.views import refresh_jwt_token
from rest_framework_jwt.views import verify_jwt_token
from django.urls import path
from accounts import views
app_name = 'accounts'
urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('', views.root, name='root'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('passwordchange/', views.passwordchangeview, name='passwordchange'),
    path('profilechange/', views.profilechange, name='profilechange'),
    # API
    
    #회원기능 1-2 \\ 로그인
    path('token/', obtain_jwt_token),
    path('token/refresh/', refresh_jwt_token),
    path('token/verify/', verify_jwt_token),



    path('signupAPI/', views.SignupView.as_view(), name='signupAPI'),
    # 다른 웹에서 호출을 하면(http://localhost:8000/accounts/signupAPI/ username=tony password='pass') 뷰단에서 입력된 메소드대로 회원가입이 이루어진다.
   
]

product/urls.py
from django.urls import path, include, re_path
from product import views




app_name = 'product'
urlpatterns = [
    path('list/', views.list, name='list'),
    path('list_add/<post_pk>', views.list_add, name='list_add'),
    path('list_remove/<post_pk>',
         views.list_remove, name='list_remove'),
    path('shop_basket/', views.shop_basket, name='shop_basket'),
    path('product_of_week/', views.product_of_week, name='product_of_week'),
    path('buying_product/<post_pk>', views.buying_product, name='buying_product'),
    path('buying_product_list/', views.buying_product_list, name='buying_product_list'),
    path('buying_delete/<post_pk>', views.buying_delete, name='buying_delete'),
    path('best_buying_product/', views.best_buying_product,
         name='best_buying_product'),


]

# <post_id> view단에서 활용 ..// <post_id>\d -> 뒤에 숫자가 온다는 의미

test_1114/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 
from accounts import views 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.root),
    path('accounts/', include('accounts.urls')),
    path('product/', include('product.urls')),
    path('product_serializer/', include('product_serializer.urls')),
    path('api-auth', include('rest_framework.urls')),
]


urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]

test_1114/templates/form.html
{% load bootstrap4 %}

            <form method = "post" action = "" enctype = "multipart/form-data">
                {% bootstrap_form form %}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">
                {{ naming|default:"Submit"}}
{% comment %} 인클루드 하는 쪽 {% include "_form.html" name = "로그인" %} {% endcomment %}
                </button>
                </form>


        

test_1114/templates/root.html
{% load static %}
<!doctype html>
<html>
<head>
<meta charset = "utf-8" />
<title> 백엔드 쇼핑몰 구축하기  </title>


{% comment %} <link rel="stylesheet" href="//stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"> {% endcomment %}
{% comment %} <link rel="stylesheet" href="{% static "bootstrap-4.5.2-dist/css/bootstrap.min.css" %}" /> {% endcomment %}
{% comment %} <script src="{% static "jquery-3.5.1.min.js" %}"></script> {% endcomment %}
{% comment %} <script src="{% static "bootstrap-4.5.2-dist/js/bootstrap.min.js" %}"></script> {% endcomment %}

<div class = "border-bottom mb-6">
        {% for m in messages %}
        {{ m.message}}
        {% endfor %}
    <div class = "container">
        <div class = "row">
            <div class = "col-sm-20">
            <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white ">
                <h5 class="my-0 mr-md-auto font-weight-normal">
                {% comment %} <svg class = "mr-2"  fill="#262626" height="22" viewBox="0 0 48 48" width="22"><path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3 3.5.1 4S0 5.2.4 5.7l13.2 13c.5.4 1.1.6 1.7.3l16.6-8c.7-.3 1.6-.1 2 .5.4.7.2 1.6-.5 2l-15.6 9.9c-.5.3-.8 1-.7 1.6l4.6 19c.1.6.6 1 1.2 1.1h.2c.5 0 1-.3 1.3-.7l23.2-39c.5-.5.5-1.1.2-1.6z"></path></svg>                 {% endcomment %}
     <nav class="my-2 my-md-0 mr-md-3">
{% if user.is_authenticated %}
<a class="p-2 text-dark" href = "{% url 'accounts:profile' %}">프로필</a> || 
<a class="p-2 text-dark" href = "{% url 'accounts:logout' %}">로그아웃</a>  ||
<a class="p-2 text-dark" href = "{% url 'product:list' %}">쇼핑</a>  || 
<a class="p-2 text-dark" href = "{% url 'product:shop_basket' %}">장바구니</a> ||
<a class="p-2 text-dark" href = "{% url 'product:buying_product_list' %}">구매물품</a> ||
<a class="p-2 text-dark" href = "{% url 'product:best_buying_product' %}">가장 많이 구매한 물품</a> ||
<a class="p-2 text-dark" href = "{% url 'product:product_of_week' %}">최근 일주일 상품</a> ||||
<a class="p-2 text-dark" href = "http://tonylee3737.pythonanywhere.com/product_serializer/api/">RestAPI 주소 </a> 
관리자페이지 아이디와 비밀번호도 동일
</nav>
<hr>
<br>
{% else %}
<a class="btn btn-outline-primary" href = "{% url 'accounts:login' %}">로그인</class=>
<a class="btn btn-outline-primary" href = "{% url 'accounts:signup' %}">회원가입</a>
<hr>
<br>
{% endif %}

{% block contents %}
{% endblock %}




 </body>
 </html>