product/urls.py
from django.urls import path, include, re_path
from product import views




app_name = 'product'
urlpatterns = [
    path('list/', views.list, name='list'),
    path('list_add/<post_pk>', views.list_add, name='list_add'),
    path('list_remove/<post_pk>',
         views.list_remove, name='list_remove'),
    path('shop_basket/', views.shop_basket, name='shop_basket'),
    path('product_of_week/', views.product_of_week, name='product_of_week'),
    path('buying_product/<post_pk>', views.buying_product, name='buying_product'),
    path('buying_product_list/', views.buying_product_list, name='buying_product_list'),
    path('buying_delete/<post_pk>', views.buying_delete, name='buying_delete'),
    path('best_buying_product/', views.best_buying_product,
         name='best_buying_product'),


]

# <post_id> view단에서 활용 ..// <post_id>\d -> 뒤에 숫자가 온다는 의미

test_1114/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings 
from accounts import views 
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.root),
    path('accounts/', include('accounts.urls')),
    path('product/', include('product.urls')),
    path('product_serializer/', include('product_serializer.urls')),
    path('api-auth', include('rest_framework.urls')),
]


urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)


# if settings.DEBUG:
#     import debug_toolbar
#     urlpatterns += [
#         path('__debug__/', include(debug_toolbar.urls)),
#     ]

product/models.py
from django.conf import settings
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator

"""
Product Model
    상품정보를 저장하는 모델. 각 상품은 다수의 상품 사진을 포함한다. 아래 첨부한 상품 데이터를 적절히 활용합니다. (날짜의 형식
    은 중요하지 않습니다.) 특히 상품 데이터는 주문자와 연결되어야 합니다.
                        """
class Product(models.Model):

    p_name = models.CharField(max_length=200)
    quantity = models.PositiveSmallIntegerField(null=True, default=1, validators=[
                                                MinValueValidator(1), MaxValueValidator(100)])
    price = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    count = models.PositiveIntegerField(null=True)
        
    def __str__(self):
        return self.p_name
    
    def plus_count(self, product):
        product.count+=1
        product.save()
        

    def sum(self):
        return self.quantity * self.price

# 사진 여러장 첨부
class Photo(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    image = models.ImageField(
        upload_to='product/%Y/%M/%D', blank=True, null=True)


"""
 Order Model
 상품의 주문정보를 저장하는 모델. 본 모델은 구매자의 구매관리 에 활용한다. (날짜의 형식은 중요하지 않습니다.)
            """
class Order(models.Model):

    basket_user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    basket_order = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(
        default=1, validators=[RegexValidator(r"^[0-9]?\d{1}$")])

    class Meta:
        ordering = ['-quantity']

    def __str__(self):
        return f'{self.basket_user}\'shop_basket'

product/views.py
from django.db.models import F
from django.db.models import Q
from django.utils import timezone
from datetime import timedelta
from product.form import OrderForm
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from product.models import Product, Order
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from accounts.models import Profile
from django.shortcuts import render
# Create your views here.


@login_required
def list(request):
    if request.method == "POST":
        q = request.POST.get('q', '')
        product = Product.objects.all().filter(p_name__icontains=q)
    else:
        product = Product.objects.all()

    # 페이지네이션
    paginator = Paginator(product, 5)
    if request.GET.get('page') == None:
        page = 1
    else:
        page = request.GET.get('page')
    product = paginator.get_page(page)
    return render(request, 'product/list.html', {
        'product': product,
        'paginator': paginator,
        'page': page,
        'form': OrderForm,
    })


def product_of_week(request):

    timesince = timezone.now() - timedelta(days=7)
    product = Product.objects.all().filter(
        created_at__gte=timesince)[::-1]
    paginator = Paginator(product, 5)
    if request.GET.get('page') == None:
        page = 1
    else:
        page = request.GET.get('page')
    product = paginator.get_page(page)
    return render(request, 'product/list.html', {
        'product': product,
        'paginator': paginator,
        'page': page,
        'form': OrderForm,
    })


@login_required
def shop_basket(request):

    product = request.user.order_set.all()

    paginator = Paginator(product, 5)
    if request.GET.get('page') == None:
        page = 1
    else:
        page = request.GET.get('page')
    product = paginator.get_page(page)
    return render(request, 'product/shop_basket.html', {
        'product': product,
        'paginator': paginator,
        'page': page,
    })


@login_required
def list_add(request, post_pk):
    product = get_object_or_404(Product, pk=post_pk)

    if request.method == "POST":
        order = OrderForm(request.POST)
        if order.is_valid():
            form = order.save(commit=False)
            form.basket_user = request.user
            form.basket_order = product
            form.save()
            messages.info(request, "상품 장바구니에 추가되었습니다.")
            return redirect('product:list')
        else:
            messages.info(request, "상품 99개 이상은 주문할 수 없습니다.")
            return redirect('product:list')


@login_required
def list_remove(request, post_pk):
    order = get_object_or_404(Order, pk=post_pk, basket_user=request.user)
    # product = Post.objects.all().filter(pk = post_pk)
    order.delete()
    messages.success(request, "장바구니에 상품을 제거하였습니다.")
    return redirect('product:shop_basket')


@login_required
def buying_product(request, post_pk):
    order = get_object_or_404(Order, pk=post_pk, basket_user=request.user)
    request.user.buying_order.add(order.basket_order)
    product = Product.objects.all().filter(pk=order.basket_order.pk)
    product[0].plus_count(product[0])
    order.delete()
    return render(request, 'product/buying_product.html', {
        'product': product[0],
        'product_count': product[0].count
    })


def buying_product_list(request):
    # product = request.user_buying_order.all
    return render(request, 'product/buying_product.html')


def buying_delete(request, post_pk):
    order = get_object_or_404(Product, pk=post_pk)
    request.user.buying_order.remove(order)
    return render(request, 'product/buying_product.html')


def best_buying_product(request):
    Product.objects.all()
    li = [n.count for n in Product.objects.all()]
    index = li.index(max(li))
    best_product = Product.objects.all()[index]
    return render(request, 'product/best_buying_product.html', {
        'best_product': best_product,
    })

product/templates/product/best_buying_product.html
{% extends 'root.html'%}

{% block contents%}


 많은 사용자가 구매한 상품 : {{ best_product }}




{% endblock %}

product/templates/product/buying_product.html
{% extends 'root.html'%}

{% block contents%}
{{product}}
||{{product_count}}
<hr>
구매물품 : <br>
<hr>
{% for p in request.user.buying_order.all%}
  {{ p }} <a href = "{% url 'product:buying_delete' p.pk%}"> || 삭제 </a><br>  
{% endfor %}





{% endblock %}

product/templates/product/list.html
{% extends 'root.html'%} 
{% comment %} {% load bootstrap4 %} {% endcomment %}
{% load humanize%}

{% block contents %}
<a href = "{% url 'product:product_of_week'%}">최신상품보기(일주일) </a>
<hr>
<div>
<form method = "POST" action = "" class = 'mb-3'>
{% comment %} {% bootstrap_form form %} {% endcomment %}
{% csrf_token %}
<input type = "text" name = 'q' > </input>
<input type = 'submit' value = "search">
</form>

</div>
<hr>
<table border = "1">
    <thead>
        <tr>
            <th>상품사진</th>
            <th>상품명</th>
            <th>상품가격</th>
            <th>주문하기</th>
        </tr>
    </thead>
            <tr>
                {% for p in product %}
         <tbody>
                <td>
                    {% for photo in p.photo_set.all %}
                    <img src = "{{ photo.image.url }}" style = "height:100px", "width:100px">  <br>
                    {% endfor %}
                </td>

            <td>{{ p.p_name }}</td>
            <td>{{ p.price|intcomma}}</td>
                <td>
                         <form method="POST" action="{% url 'product:list_add' p.pk %} " enctype="multipart/form-data">
                        {{form.as_p }} 
                        {% csrf_token %}
                        <input type="submit" value="주문하기">
                        </form>
           
                </td>
            {% endfor %}
    </tbody>
        </tr>
</table>
<hr>
{% if product.previous_page_number > 0 %}
<a href="?page={{ product.previous_page_number}} " > 이전</a>
{% endif %}
현재: {{page}}
{% if product.has_next %}
<a href="?page={{ product.next_page_number}} " > 다음</a>
{% else %}        
        마지막
{% endif %}


{% endblock %}

product/templates/product/shop_basket.html
{% extends 'root.html'%}
{% block contents %}

{{user}}' 장바구니
<hr>


{% for p in product %}
<div>
주문 상품 : {{p.basket_order}} | <a href = "{% url 'product:list_remove' p.pk %}">반환</a>),
개수: {{p.quantity}}
<a href = "{% url 'product:buying_product' p.pk %}">구매하기</a>
<hr>
</div>
{% endfor %} 
<hr>
{% if product.previous_page_number > 0 %}
<a href="?page={{ product.previous_page_number}} " > 이전</a>
{% endif %}
현재: {{page}}
{% if product.has_next %}
<a href="?page={{ product.next_page_number}} " > 다음</a>
{% else %}        
        마지막
{% endif %}


{% endblock %}